services:
  backend:
    build:
      context: .
    container_name: shopping-backend
    networks:
      - shopnet
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres
    container_name: shopping-db
    networks:
      - shopnet
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: shoppingdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d shoppingdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    image: maeddes/frontendflask:hft24
    container_name: shopping-frontend
    networks:
      - shopnet
    ports:
      - "5000:5000"
    depends_on:
      - backend
    environment:
      SPRING_BOOT_API_URL: http://backend:8080/api/shoppingItems

networks:
  shopnet:
    name: shopnet

volumes:
  postgres-data:
