apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-api-backend-go
  labels:
    app: shopping-api-backend-go
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shopping-api-backend-go
  template:
    metadata:
      labels:
        app: shopping-api-backend-go
    spec:
      containers:
      - name: shopping-api-backend-go
        image: docker.io/sathyapriyap12/shopping-api-backend-go:latest
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRES_HOST
          value: "shopping-db.default.svc.cluster.local"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: "admin"
        - name: POSTGRES_PASSWORD
          value: "mypassword"
        - name: POSTGRES_DB
          value: "shoppingdb"
