apiVersion: v1
kind: Service
metadata:
  name: shopping-db  # Service name for the database
spec:
  selector:
    app: shopping-db
  ports:
    - protocol: TCP
      port: 5432  # Expose PostgreSQL default port
      targetPort: 5432  # Forward to container's port
  type: ClusterIP  # Internal communication within the cluster
