apiVersion: v1
kind: Service
metadata:
  name: shopping-api-service
spec:
  selector:
    app: shopping-api-backend-go
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
