apiVersion: v1
kind: Service
metadata:
  name: shopping-api-service
spec:
  selector:
    app: shopping-api-backend-go
  type: NodePort  # Use NodePort for exposing
  ports:
    - protocol: TCP
      port: 80  # Service port
      targetPort: 8080  # Container port
      nodePort: 30007  # Exposed on all nodes at this port
