name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop      # Add other branches like develop for staging if needed
  pull_request:
    branches:
      - main
      - develop      # Add other branches like develop for staging if needed

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [development, production]  # Can expand to staging, testing, etc.

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx (for advanced build options)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Step 3: Load environment-specific variables (e.g., .env.development, .env.production)
      - name: Load environment variables
        run: |
          echo "Loading .env.${{ matrix.environment }} file"
          if [ -f .env.${{ matrix.environment }} ]; then
            set -o allexport
            source .env.${{ matrix.environment }}
            set +o allexport
          else
            echo ".env.${{ matrix.environment }} file not found. Exiting."
            exit 1
          fi

      # Step 4: Log in to Docker Hub using GitHub Secrets
      - name: Log in to Docker Hub
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      # Step 5: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/shopping-backend:${{ matrix.environment }} .

      # Step 6: Push the Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/shopping-backend:${{ matrix.environment }}
